package:
  name: mpi4py
  version: 1.3.1

source:
  git_url: https://bitbucket.org/mpi4py/mpi4py.git
  git_tag: 1.3.1

requirements:
  build:
    - python
    - cython
    - openmpi
  run:
    - python
    - openmpi

test:
  imports:
    - mpi4py

about:
  home: https://bitbucket.org/mpi4py/mpi4py
  license: New BSD




