package:
  name: trilinos
  version: 12.10.1

source:
  fn: trilinos-12.10.1-Source.tar.bz2
  url: https://trilinos.org/oldsite/download/files/trilinos-12.10.1-Source.tar.bz2
  md5: 1e14df93afaddb12cf840da56c5132ce

build:
  number:
   2

requirements:
  build:
    - python
    - numpy {{ numpy }}
    - swig ==3.0.10
    - cmake
    - mpich
    - openblas
    - boost
  run:
    - python
    - {{ pin_compatible('numpy', max_pin=None) }}
    - mpich
    - openblas

test:
  imports:
    - PyTrilinos
    - PyTrilinos._Teuchos
    - PyTrilinos.ML
