package:
  name: trilinos
  version: 11.10.2

source:
  fn: trilinos-11.10.2-Source.tar.bz2
  url: http://trilinos.sandia.gov/download/files/trilinos-11.10.2-Source.tar.bz2
  md5: c8dd5012890140b1a98c704c111cddaa

requirements:
  build:
    - python
    - numpy
    - swig 2.0.8
    - cmake
  run:
    - python
    - numpy

test:
  imports:
    - PyTrilinos
    - PyTrilinos._Teuchos
